### ISSUE TITLE
Problem with Type=Checkbox attributes

### ISSUE THREAD

**Issue by shushry** [michield/phplist-plugin-attributeselect#1] opened 2013-06-20 16:41 UTC
I'm using version 0.1 with phplist 2.11.9, and in a test list with a 'test' attribute (type=checkbox, default off, half the list is set to  'on') - attempting to send to the list with my attribute checkbox = on as the criteria.

Process queue runs, but no email is ever sent to any list recipients, though i'm expecting the half with "attribute = on" to get one.

Sending to the list with no criteria set works as expected.

**Comment by shushry** [comment] 2013-06-20 17:01
Update:   Upgraded to the latest dev build - 2.11.10 - same result.

**Comment by shushry** [comment] 2013-06-20 19:22
Update2:  Looks like this plugin is choking when the criteria/attribute type is a checkbox.    I added a yes/no attribute of type = SELECT (which essentially emulates a checkbox with a yes or no) and the plugin worked fine.

MySQL seems to be complaining about the query generated around the selection query with:

Database error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Database error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'off\' and table1.value != \'0\')' at line 1

**Comment by michield** [comment] 2013-06-20 22:27
great. sounds like you're close to finding the cause for it. I may have some time next week to look at it, but if you can find it in the meantime, will be great.

**Comment by michield** [comment] 2013-06-24 20:19
I think it's fixed now, but feel free to open a new issue if not

**Closed as completed by michield** 2013-06-24 20:19 UTC
